# Generated by Django 4.0.4 on 2022-06-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvy_blog', '0002_alter_savvyblogpage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='savvyblogpage',
            name='snipit',
            field=models.TextField(blank=True),
        ),
    ]
