# Generated by Django 4.0.4 on 2022-06-03 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savvy_blog', '0003_savvyblogpage_snipit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savvyblogpage',
            old_name='snipit',
            new_name='snippit',
        ),
    ]
