# Generated by Django 4.0.4 on 2022-06-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('savvy_blog', '0005_savvyblogpage_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savvyblogpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
