# Generated by Django 4.0.4 on 2022-06-03 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savvy_blog', '0007_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='savvyblogpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='savvy_blog.author'),
        ),
    ]
