# Generated by Django 4.0.4 on 2022-06-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savvy_blog', '0008_savvyblogpage_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savvyblogpage',
            old_name='snippit',
            new_name='snippet',
        ),
    ]
